from dotenv import load_dotenv
import os
import psycopg2

load_dotenv()

DB_URL = os.environ["DATABASE_URL"]

create_private_schema = """
CREATE SCHEMA IF NOT EXISTS private;
"""

create_speakers_table = """
CREATE TABLE IF NOT EXISTS private.speakers (
    speaker_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    speaker_name TEXT,
    speaker_party TEXT,
    UNIQUE (speaker_name, speaker_party)
);"""

create_files_table = """
CREATE TABLE IF NOT EXISTS private.files (
    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    file_date DATE,
    file_year INTEGER,
    source TEXT NOT NULL,
    CONSTRAINT cource_check CHECK (source IN ('bundestag', 'talkshow')),
    UNIQUE (file_name)
);"""

create_topics_table = """
CREATE TABLE IF NOT EXISTS private.topics (
    topic_id INTEGER NOT NULL PRIMARY KEY,
    topic_keywords TEXT,
    topic_label TEXT,
    topic_duration INTERVAL NOT NULL DEFAULT INTERVAL '0',
    topic_duration_bt INTERVAL NOT NULL DEFAULT INTERVAL '0',
    topic_duration_ts INTERVAL NOT NULL DEFAULT INTERVAL '0',
    UNIQUE (topic_keywords, topic_label)
);"""

create_table_speeches = """
CREATE TABLE IF NOT EXISTS private.speeches (
    speech_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    speech_key TEXT NOT NULL,
    speech_text TEXT,
    speech_duration INTERVAL,
    file BIGINT,
    speaker BIGINT,
    topic INTEGER,
    CONSTRAINT fk_file FOREIGN KEY (file) REFERENCES private.files(file_id),
    CONSTRAINT fk_speaker FOREIGN KEY (speaker) REFERENCES private.speakers(speaker_id),
    CONSTRAINT fk_topic FOREIGN KEY (topic) REFERENCES private.topics(topic_id),
    UNIQUE (speech_key)
);"""

default_speaker = """
INSERT INTO private.speakers (speaker_name, speaker_party)
VALUES ('Unknown', 'Unknown')
ON CONFLICT (speaker_name, speaker_party) DO NOTHING;
"""

function_trigger_insert = """
CREATE OR REPLACE FUNCTION private.trgfn_topic_duration_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE private.topics
    SET topic_duration = topic_duration + coalesce(NEW.speech_duration, INTERVAL '0')
    WHERE topic_id = NEW.topic;
    
    UPDATE private.topics
    SET topic_duration_bt = topic_duration_bt + coalesce(NEW.speech_duration, INTERVAL '0')
    WHERE topic_id = NEW.topic
        AND EXISTS (
            SELECT 1
            FROM private.files f
            WHERE f.file_id = NEW.file AND f.source = 'bundestag'
        );
    
    UPDATE private.topics
    SET topic_duration_ts = topic_duration_ts + coalesce(NEW.speech_duration, INTERVAL '0')
    WHERE topic_id = NEW.topic
        AND EXISTS (
            SELECT 1
            FROM private.files f
            WHERE f.file_id = NEW.file AND f.source = 'talkshow'
        );
    
    RETURN NEW;
END;
$$;"""

function_trigger_update = """
CREATE OR REPLACE FUNCTION private.trgfn_topic_duration_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE private.topics
    SET topic_duration = topic_duration - coalesce(OLD.speech_duration, INTERVAL '0')
    WHERE topic_id = OLD.topic;
    UPDATE private.topics
    SET topic_duration = topic_duration + coalesce(NEW.speech_duration, INTERVAL '0')
    WHERE topic_id = NEW.topic;
    
    UPDATE private.topics
    SET topic_duration_bt = topic_duration_bt - coalesce(OLD.speech_duration, INTERVAL '0')
    WHERE topic_id = OLD.topic
        AND EXISTS (
            SELECT 1
            FROM private.files f
            WHERE f.file_id = OLD.file AND f.source = 'bundestag'
        );
    UPDATE private.topics
    SET topic_duration_bt = topic_duration_bt + coalesce(NEW.speech_duration, INTERVAL '0')
    WHERE topic_id = NEW.topic
        AND EXISTS (
            SELECT 1
            FROM private.files f
            WHERE f.file_id = NEW.file AND f.source = 'bundestag'
        );
    
    UPDATE private.topics
    SET topic_duration_ts = topic_duration_ts - coalesce(OLD.speech_duration, INTERVAL '0')
    WHERE topic_id = OLD.topic
        AND EXISTS (
            SELECT 1
            FROM private.files f
            WHERE f.file_id = OLD.file AND f.source = 'talkshow'
        );
    UPDATE private.topics
    SET topic_duration_ts = topic_duration_ts + coalesce(NEW.speech_duration, INTERVAL '0')
    WHERE topic_id = NEW.topic
        AND EXISTS (
            SELECT 1
            FROM private.files f
            WHERE f.file_id = NEW.file AND f.source = 'talkshow'
        );
    
    RETURN NEW;
END;
$$;"""

function_trigger_delete = """
CREATE OR REPLACE FUNCTION private.trgfn_topic_duration_delete()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE private.topics
    SET topic_duration = topic_duration - coalesce(OLD.speech_duration, INTERVAL '0')
    WHERE topic_id = OLD.topic;
    
    UPDATE private.topics
    SET topic_duration_bt = topic_duration_bt - coalesce(OLD.speech_duration, INTERVAL '0')
    WHERE topic_id = OLD.topic
        AND EXISTS (
            SELECT 1
            FROM private.files f
            WHERE f.file_id = OLD.file AND f.source = 'bundestag'
        );
    
    UPDATE private.topics
    SET topic_duration_ts = topic_duration_ts - coalesce(OLD.speech_duration, INTERVAL '0')
    WHERE topic_id = OLD.topic
        AND EXISTS (
            SELECT 1
            FROM private.files f
            WHERE f.file_id = OLD.file AND f.source = 'talkshow'
        );
    
    RETURN NEW;
END;
$$;"""

trigger_insert_drop = """
DROP TRIGGER IF EXISTS trg_topic_duratoin_insert ON private.speeches;"""

trigger_insert = """
CREATE TRIGGER trg_topic_duration_insert
AFTER INSERT ON private.speeches
FOR EACH ROW
EXECUTE FUNCTION private.trgfn_topic_duration_insert();"""

trigger_update_drop = """
DROP TRIGGER IF EXISTS trg_topic_duration_update ON private.speeches;"""

trigger_update = """
CREATE TRIGGER trg_topic_duration_update
AFTER INSERT ON private.speeches
FOR EACH ROW
EXECUTE FUNCTION private.trgfn_topic_duration_update();"""

trigger_delete_drop = """
DROP TRIGGER IF EXISTS trg_topic_duration_delete ON private.speeches;"""

trigger_delete = """
CREATE TRIGGER trg_topic_duration_delete
AFTER INSERT ON private.speeches
FOR EACH ROW
EXECUTE FUNCTION private.trgfn_topic_duration_delete();"""


with psycopg2.connect(DB_URL) as conn:
    with conn.cursor() as cur:
        cur.execute(create_private_schema)
        cur.execute(create_speakers_table)
        cur.execute(create_files_table)
        cur.execute(create_topics_table)
        cur.execute(create_table_speeches)
        cur.execute(default_speaker)
        cur.execute(function_trigger_insert)
        cur.execute(function_trigger_update)
        cur.execute(function_trigger_delete)
        cur.execute(trigger_insert_drop)
        cur.execute(trigger_insert)
        cur.execute(trigger_update_drop)
        cur.execute(trigger_update)
        cur.execute(trigger_delete_drop)
        cur.execute(trigger_delete)
    conn.commit()

print("Database and tables created successfully.")